[FEAT] Kakao Login Init Setting
HongDam-org/TWTW pull request #1
Opened 2023-08-03 07:09 UTC by jinjoo-lab

Kakao Login 구현을 위한 기본 세팅
: Oauth2 의존성 추가

2023-08-03 11:58 UTC, ohksj77 approved these changes
세팅이라서 빡세게 코드를 안짠거 같긴 한데 그래도 코멘트 한 번씩 읽어줘!

2023-08-03 11:58 UTC, ohksj77 commented on backend/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
지금 추가한 이 부분은 우리 설계상 필요 없을 거 같아!

2023-08-03 11:58 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/jwt/JwtToken.java
> +    public JwtToken(String accessToken,String refreshToken)
우리 롬복 사용하니까 클래스 단위에 builder랑 AllArgs 생성자 붙이는거 어떄?

2023-08-03 11:58 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/entity/OAuth2Info.java
> +    public boolean equals(Object o) {
우리 이 방식 사용하는거 어때? lombok으로 equals & hashcode 생성하는거
[reference](https://junhyunny.github.io/information/java/equals-and-hashcode/)

2023-08-03 11:58 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/entity/OAuth2Info.java
> +@NoArgsConstructor
요고 PROTECTED로 해야하지 않나..?

2023-08-03 11:58 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/jwt/JwtToken.java
> +    }
나는 중괄호 메서드 밑 말고 바로 오른쪽에서 열고 싶은데 이거 통일하는게 좋지 않을까?
내가 말한 방식이 java에서 기본으로 따르는 java google 컨벤션이랑 맞기도 해..!

2023-08-03 11:58 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/entity/Member.java
> +
생성자는 나중에 만들어줘

2023-08-03 14:38 UTC, jinjoo-lab commented on backend/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
Check

2023-08-03 14:38 UTC, jinjoo-lab commented on backend/src/main/java/com/twtw/backend/module/member/entity/OAuth2Info.java
> +@NoArgsConstructor
Check

2023-08-03 14:38 UTC, jinjoo-lab commented on backend/src/main/java/com/twtw/backend/module/member/entity/Member.java
> +
OK

2023-08-07 15:28 UTC, ohksj77 requested changes
전반적으로 중괄호가 메서드에서는 내가 피드백한대로 열었는데 if 나 다른 곳에서는 안그렇더라고ㅠ
자바가 따라가는 스타일을 따르는 것도 어느정도 나쁘지 않다고 보거든! 

일일이 신경쓰기 번거로울 수 있으니 google 코드 스타일로 포매팅 해주는거 깃허브 액션으로 하는거 어때? 괜찮다고 하면 내가 할게!

+ 12:34 도메인을 묶는 패키지를 module 말고 domain 으로 하는거 어때?

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/SecurityConfig.java
> +                        x->x.requestMatchers("/test/**")
테스트에서 토큰 인증을 안쓰려고..? 나는 쓰는게 좋다고 생각함

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/entity/RefreshToken.java
> +    }
일단 config.security 패키지에 엔티티 & 레포지토리 넣는거 좋지 않은 것 같아
그리고 refreshToken을 Entity로 만들 이유가 있을까?

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/entity/RefreshToken.java
> +    }
비즈니스 로직을 도메인에 넣고 싶어서 만든거면 embedded로 충분할거 같은데 비즈니스 로직도 안보여서..

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/jwt/TokenProvider.java
> +            throw new RuntimeException("권한 정보가 없는 토큰입니다.");
RuntimeException 에 String으로 메시지 넣고 던지는거 좀 올드한 패턴이라서.. 차라리 exception을 만드는거 어때?

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/config/security/repository/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken,String> {
이거는 엔티티 없앨거면 이거도 같이 없애기!

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/controller/AuthController.java
> +@RequestMapping("/auth")
나중에 WebServer 쓸거면 /api 붙여야하지 않을까? 공통된 api url 부분을 application.yml 에서 설정할 수 있어

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/controller/AuthController.java
> +        this.authService = authService;
이정도는 그냥 lombok 쓰자..

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/controller/AuthController.java
> +        if(tokenDto == null){
이렇게 controller에서 분기하기 보다는 그냥 없을때 로직 자체에서 예외 던지고 예외 안던져졌을때만 정상 response 하는게 좋을듯

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/entity/AuthType.java
> +@Getter
필드가 없는데 getter는 왜 있는건감..

2023-08-07 15:28 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/service/AuthService.java
> +        member = memberRepository.save(member);
그리고 기존 member 엔티티에 할당하는 방법 말고 다른 방법 없을까

2023-08-07 15:36 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/controller/AuthController.java
> +        if(tokenDto == null){
애초에 controller에 많은 책임을 주는게 좋지 않아.. 하는 일이 많아 ㅜㅜ 나는 되도록 inline 할 수 있으면 해서 한 줄로 끝내려고 하는편!

2023-08-07 15:37 UTC, ohksj77 commented on backend/src/main/java/com/twtw/backend/module/member/dto/request/TokenRequest.java
> +    String refreshToken;
뭐야 RequiredArgs 가 있는데 final 은 없네..

2023-08-07 17:41 UTC, ohksj77 commented
일단 확인했고 해결된 부분들 resolve 눌러 놨어
안누른 부분들은 틀린게 아니라 논의해볼 만한 부분들이라서 한 번 논의해보자

2023-08-09 06:59 UTC, ohksj77 approved these changes

2023-08-09 07:00 UTC, merged